version: "3.7"

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - .:/app
    depends_on:
      - web

  mysql:
    image: mysql:8.0.25
    build:
      context: ./docker/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    ports:
      - '6001:6001'
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/app

  #  pgsql:
  #    image: postgres:13
  #    restart: unless-stopped
  #    ports:
  #      - '5432:5432'
  #    volumes:
  #      - pgsql_data:/var/lib/postgresql
  #    environment:
  #      POSTGRES_DB: ${DB_DATABASE}
  #      POSTGRES_USER: ${DB_USERNAME}
  #      POSTGRES_PASSWORD: ${DB_PASSWORD}

  redis:
    image: redis:6.0
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
  meilisearch_data:
